# Tensors 

In [1]:
import torch
import numpy as np

## Initializing a tensor

In [2]:
# From python list, and the datatype is int64
data = [[1,2], [3,4]]
x_data = torch.tensor(data)

In [8]:
print(x_data)
x_data.dtype

tensor([[1, 2],
        [3, 4]])


torch.int64

In [9]:
# From numpy ndarray, and the datatype is int64
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [10]:
x_np

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [11]:
x_zeros = torch.zeros_like(x_data)
print(f"Zeros Tensor: \n {x_zeros} \n")

x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Zeros Tensor: 
 tensor([[0, 0],
        [0, 0]]) 

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.7508, 0.7330],
        [0.1404, 0.1784]]) 

